const descriptions = {
  ÅtrstnL: "beskrivning ÅtrstnL",
  Hastght: "beskrivning Hastght",
  DoU2017: "beskrivning DoU2017",
  ÅDT_tng: "beskrivning ÅDT_tng",
  ÅDT_mtr: "beskrivning ÅDT_mtr",
  Vägnmmr: "beskrivning Vägnmmr",
  Vägktgr: "Vägktgr beskrivning här",
  Vägtyp: "beskrivning Vägtyp",
  Längd: "beskrivning Längd",
  Blggnngst: "beskrivning Blggnngst",
  Län_nr: "beskrivning Län_nr",
  Kmmn_nr: "beskrivning Kmmn_nr",
  Trfkkls: "beskrivning Trfkkls",
  IRI_ndr: "beskrivning IRI_ndr",
  Sprdjp_: "beskrivning Sprdjp_",
  Region: "beskrivning Region",
  Ålder: "beskrivning Ålder",
  FrvntdL: "beskrivning FrvntdL",
  TllstnI: "beskrivning TllstnI",
  IndxKls: "beskrivning IndxKls",
  ÅDT_frd: "beskrivning ÅDT_frd",
  Spårdjp: "beskrivning Spårdjp",
  IRI: "beskrivning IRI",
  Vägbrdd: "beskrivning Vägbrdd",
  Brghtsk: "beskrivning Brghtsk",
  Byear: "beskrivning Byear",
  Bmonth: "beskrivning Bmonth",
  Bday: "beskrivning Bday",
  Myear: "beskrivning Myear",
  Mmonth: "beskrivning Mmonth",
  Mday: "beskrivning Mday",
  IndK2030: "beskrivning IndK2030",
  IKls_2: "beskrivning IKls_2",
  IKls_3: "beskrivning IKls_3",
};

export default descriptions;
